# Generated by Django 4.2.1 on 2023-06-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
