# Generated by Django 4.2.1 on 2023-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('ranking', models.PositiveIntegerField()),
                ('lp', models.PositiveIntegerField()),
                ('win_rate', models.FloatField()),
            ],
        ),
    ]
