# Generated by Django 4.2.1 on 2023-05-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='ranking',
            new_name='rank',
        ),
    ]
