# Generated by Django 4.2.1 on 2023-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0002_rename_ranking_summoner_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='icon_url',
            field=models.IntegerField(),
        ),
    ]
