# Generated by Django 4.2.1 on 2023-05-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0005_alter_summoner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='win_rate',
            field=models.CharField(max_length=10),
        ),
    ]
