# Generated by Django 4.2.1 on 2023-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0006_alter_summoner_win_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='rank',
            new_name='ranking',
        ),
        migrations.AlterField(
            model_name='summoner',
            name='lp',
            field=models.IntegerField(default=0),
        ),
    ]
