# Generated by Django 4.2.1 on 2023-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0007_rename_rank_summoner_ranking_alter_summoner_lp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
