# Generated by Django 4.2.1 on 2023-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0008_alter_summoner_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='tier',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='lp',
            field=models.IntegerField(),
        ),
    ]
