# Generated by Django 4.2.1 on 2023-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0009_summoner_tier_alter_summoner_lp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='lp',
            field=models.IntegerField(null=True),
        ),
    ]
