# Generated by Django 4.2.1 on 2023-05-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('wins', models.IntegerField()),
                ('pick_rate', models.FloatField()),
                ('ban_rate', models.FloatField()),
                ('cs', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.champion')),
            ],
        ),
    ]
