# Generated by Django 4.2.1 on 2023-05-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstats',
            name='cs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='championstats',
            name='wins',
            field=models.FloatField(),
        ),
    ]
