# Generated by Django 4.2.1 on 2023-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_rename_rating_championstats_kda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstats',
            name='gold',
            field=models.IntegerField(),
        ),
    ]
