# Generated by Django 4.2.1 on 2023-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_alter_championstats_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='en_name',
            field=models.CharField(default='ee', max_length=100),
        ),
    ]
